name: catgram
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  faker: ^2.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.4
  intl: ^0.17.0
  octo_image: ^1.0.1
  path_provider: ^2.0.9
  share_plus: ^4.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Cookie
      fonts:
        - asset: fonts/Cookie-Regular.ttf
flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#000000"